version: '3.9'

services:
  skc-site:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx, '-g', 'daemon off;']
    restart: always
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - skc-network
    environment:
      NODE_ENV: production

networks:
  skc-network:
    name: skc-network
    driver: bridge
